// GENERATED from spec.json by scripts/gen-consts.mjs — DO NOT EDIT.
// interface: tslot_2020 v0.1.0

PROFILE__SIZE = 20;
PROFILE__SLOT_GAP = 6;
PROFILE__SLOT_DEPTH = 6;
PROFILE__BORE_D = 4.2;
PROFILE__SIZE_2040 = 40;
TNUT__BODY_W = 5.8;
TNUT__BODY_T = 3.2;
TNUT__STEM_THREAD = 5;
TNUT__LENGTH = 12;
BRACKET__HOLE_PITCH = 20;
BRACKET__HOLE_D = 5;
BRACKET__THICKNESS = 3;
BRACKET__LEG = 20;
